baseurl = "https://beveloper.fr"
languageCode = "fr-fr"
Title = "Beveloper"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; vcasse"
custom_css = "/static/css/custom.css"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "vcasse"
  github = "VincentCasse"
  youtube = "https://www.youtube.com/playlist?list=PLrXG4T5_9fsh_1BIoaMwn45IKyytfD0rs"
  linkedin = "vcasse"
  author = "Vincent Cassé"
  authorwebsite = "beveloper.fr"
  bio = "Hôte pour des millions de sites web. Petits dej et HTTPS inclus. Arrivée à toute heure du jour ou de la nuit"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Because software is eating the world"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
